name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    
    steps:
     
    - name: Checkout Code
      uses: actions/checkout@v3

     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

     
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     
    - name: Build Docker image
      run: |
        docker build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/386,macos/amd64 -t jigmetsd/doc-to-pdf-converter:latest .

 
    - name: Push Docker image
      run: |
        docker push jigmetsd/doc-to-pdf-converter:latest
